root: true

env:
  node: true
  es6: true

extends:
  - eslint:recommended
  - plugin:vue/recommended
  - plugin:prettier/recommended

parserOptions:
  sourceType: module
  allowImportExportEverywhere: true

ignorePatterns:
  - node_modules/
  - iconpacks/
  - ./assets/
  - .nuxt/
  - docs/dist/
  - src/icons/
  - demo/

rules:
  no-unused-vars:
    - 2
    - vars: all
      args: none
  vue/no-v-html: 0
  vue/component-definition-name-casing: 0
  vue/require-default-prop: 0
  vue/require-prop-types: 0
  prettier/prettier:
    - error
    - trailingComma: none
